name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      GITHUB_RUN_NUMBER: $(GITHUB_RUN_NUMBER)
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
